### ISSUE TITLE
Datepicker disappears when clicking scroll bar and doesn't return when clicking in input box again

### ISSUE THREAD

**Issue by nomanalikhan** [YouCanBookMe/react-datetime#283]
This only happens when you click on the scroll-bar on a page. When you click, the picker disappears, but the input box doesn't lose focus. Now if you click back into the input box (which still has focus) the picker will not pop open. You have to click outside the box to blur it, then click back in. If you click outside the input box anywhere else besides the scroll bar, then the input box loses focus.

Tried on multiple browsers, no luck :(

**Comment by kkurdupov** [comment]
I don't understand why this issue is not fixed yet. This is really annoying.
I encountered a similar issue. Let me explain:
I have a picker:
<DateTimePicker timeFormat={false} utc={true}/>
When you click the picker's input - picker opens, but if you click the input again - picker closes. The input doesn't lose focus, but picker closes - **I am not sure this is correct behavior.**
The reason is **handleClickOutside** function in **DateTime.js** file. The function checks if the statement - _**if ( this.props.input && this.state.open && !this.props.open ) {**_ is true.
I think it must be expanded with two more checks:
1) If user clicks on not the picker's input.
2) if picker's input has no focus.

**Comment by layneanderson** [comment]
Fixed on v2.11.0

**Comment by LeoFengNY** [comment]
tried to use v2.11.0, it was not fixed, the issue still exist.

**Comment by arqex** [comment]
This should be fixed on v3.0.4.
