### ISSUE TITLE
Package loads react typing for yet unreleased react version

### ISSUE THREAD

**Issue by andrejsm** [YouCanBookMe/react-datetime#425]
### I'm Submitting a ...
```
[x] Bug report
[ ] Feature request
[ ] Support request
```

### Steps to Reproduce
Fairly simple, just save `@types/react ^15.0` to your packages along with `react-datetime ^2.10` and you will get problems like `expected type 'SVGProps<SVGFETileElement>', but here has type 'SVGProps<SVGFETileElement>'` which is caused by mismatch of `@typings/react` versions.

Since react v16 is not released yet, we are using v15 and accordingly proper typings version, but due to `react-dateime` deps definition, it loads typings v16 which is released already.

Not asking this to be fixed, as I believe react v16 will be released soon. To fix the issue, just add stricter rules to load typings lower than v16 (at this line https://github.com/YouCanBookMe/react-datetime/blob/master/package.json#L47)

**Comment by cwmacdon** [comment]
This should be fixed by https://github.com/YouCanBookMe/react-datetime/pull/409

**Comment by andrejsm** [comment]
Unfortunately it's not fixed. I'm having this issue during development. For now I've forked and updated version lock to restrict anything outside v15 and it works.

**Comment by cwmacdon** [comment]
Yeah sorry I will be more clear - #409 has been merged but there hasn't been a new release yet that includes it.

**Comment by simeg** [comment]
@andrejsm @cwmacdon: The #409 change has now been released in version 2.10.2. Please let me know if this resolved your issues @andrejsm.

**Comment by simeg** [comment]
Closing due to inactivity.
